# Matryoshka SAE Configuration for Euclid Q1 Dataset
# This file contains all configuration parameters for training and evaluating
# the Matryoshka Sparse Autoencoder on Euclid galaxy embeddings.

[model]
# Input dimension (matches ZooBot encoder output)
input_dim = 640

# Matryoshka group sizes - defines the hierarchical structure  
group_sizes = [64, 64, 128, 256, 512, 1024]

# Number of top features to keep active per example
top_k = 64

# L1 regularization coefficient for sparsity
l1_coeff = 0.001

# Auxiliary loss penalty for dead feature revival
aux_penalty = 0.03

# Number of batches before considering a feature "dead"
n_batches_to_dead = 256

# Multiplier for auxiliary reconstruction (dead feature revival)
aux_k_multiplier = 16

[training]
# Training parameters
epochs = 200
learning_rate = 0.0001
batch_size = 256

# Device selection (auto-detected if not specified)
device = "auto"  # "cuda", "cpu", or "auto"

[data]
# Huggingface dataset configuration
dataset_name = "mwalmsley/gz_euclid"
train_embedding_path = "./results/euclid_train_embeddings.npy"
train_ids_path = "./results/euclid_train_ids.npy"
test_embedding_path = "./results/euclid_test_embeddings.npy"
test_ids_path = "./results/euclid_test_ids.npy"

# Random seed for reproducibility
random_seed = 42

[output]
# Output directories (relative to project root)
results_dir = "./results/sae"
model_filename = "matryoshka_sae_final.pth"

# Weights & Biases logging
wandb_project = "euclid-q1-matryoshka-sae"

[visualization]
# Feature visualization parameters
max_features_to_visualize = 64
top_images_per_feature = 30
